# 510x298 (151980)
mesh:
- direction: x
  start: -15.0
  subDomains:
  - cells: 111
    end: -0.75
    stretchRatio: 0.9708737864
  - cells: 90
    end: 0.75
    stretchRatio: 1.0
  - cells: 309
    end: 35.0
    stretchRatio: 1.01
- direction: y
  start: -25.0
  subDomains:
  - cells: 104
    end: -0.75
    stretchRatio: 0.9615384615
  - cells: 90
    end: 0.75
    stretchRatio: 1.0
  - cells: 104
    end: 25.0
    stretchRatio: 1.04

flow:
  nu: 0.01
  initialVelocity: [1.0, 0.0, 0.0]
  boundaryConditions:
  - location: xMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
  - location: xPlus
    u: [CONVECTIVE, 1.0]
    v: [CONVECTIVE, 1.0]
  - location: yMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
  - location: yPlus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]

parameters:
  dt: 0.01
  startStep: 0
  nt: 20000
  nsave: 1000
  nrestart: 5000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
- type: points
  name: cylinder
  file: cylinder.body

probes:
- name: probe-p
  type: VOLUME
  field: p
  viewer: hdf5
  path: solution/probe-p.h5
  n_sum: 1000
  box:
    x: [-0.75, 0.75]
    y: [-0.75, 0.75]
